apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: rest-tfserving
spec:
  name: resttfserving
  protocol: tensorflow
  transport: rest
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - args:
          - --port=8500
          - --rest_api_port=8501
          - --model_name=half-plus-two
          - --model_base_path=gs://seldon-models/tfserving/half-plus-two
          image: sreddybr3/tfs-prebaked:0.0.3
          name: half-plus-two
          ports:
          - containerPort: 8501
            name: http
    graph:
      name: half-plus-two
      type: MODEL
      endpoint:
        service_port: 8501
    name: model
    replicas: 1